language: cpp

branches:
  only:
  - master

jobs:
  include:
    - stage: Build&Test
      name: Linux PCMockup
      script: bash ./travis/cmake_script.sh
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-8
    - stage: Build&Test
      name: Pebble
      before_script: bash ./travis/pebble_before_script.sh
      script: bash ./travis/pebble_script.sh
      cache:
        directories:
          - $HOME/pebble-dev
          - $HOME/.cache/pip
          - $HOME/.pebble-sdk

addons:
  apt:
    packages:
    - python2.7-dev
    - python-pip
    - python-virtualenv
    - libegl1-mesa-dev
    - libgles2-mesa-dev
    - libsdl2-dev
