language: cpp

branches:
  only:
  - travis_ci

addons:
  apt:
    packages:
    - cmake
    - gcc-6
    - libsdl2-dev

script:
  - mkdir -p build
  - cd build
  - cmake
  - make
  - ./test_podrenderer
