language: cpp
sudo: false

branches:
  only:
  - master

jobs:
  include:
    - stage: Build&Test
      name: Linux PCMockup
      script: bash ./travis/cmake_script.sh

addons:
  apt:
    packages:
    - python2.7-dev
    - python-pip
    - python-virtualenv
    - libegl1-mesa-dev
    - libgles2-mesa-dev
    - libsdl2-dev
