language: cpp

branches:
  only:
  - travis_ci

before_install:
  - sudo apt-get install -y libegl1-mesa-dev libgles2-mesa-dev
  - sudo apt-get install -y libsdl2-dev

script:
  - mkdir -p build
  - cd build
  - cmake ..
  - make
  - ./test_podrenderer
