language: cpp
sudo: false

branches:
  only:
  - master

script:
  - mkdir -p build
  - cd build
  - cmake ..
  - make
  - ctest

addons:
  apt:
    packages:
    - python2.7-dev
    - python-pip
    - python-virtualenv
    - libegl1-mesa-dev
    - libgles2-mesa-dev
    - libsdl2-dev
