#ifndef RESOURCES_H
#define RESOURCES_H

#ifndef POD_PEBBLE
enum {
    RESOURCE_ID_SPR_BOOK = 1,
    RESOURCE_ID_ICON_DIGITS,
    RESOURCE_ID_ICON_BOOTS,
    RESOURCE_ID_ICON_GOLD,
    RESOURCE_ID_SPR_HEART, // actually double-duty as icon
    RESOURCE_ID_ICON_KEY,
    RESOURCE_ID_ICON_USE,
    RESOURCE_ID_ICON_FIST,
    RESOURCE_ID_ICON_SPEAK,
    RESOURCE_ID_ICON_BATTERY,
    RESOURCE_ID_SPR_BATTERY,
    RESOURCE_ID_SPR_KEY,

    RESOURCE_ID_SPR_PC,
    RESOURCE_ID_SPR_PC_PUSH,
    RESOURCE_ID_SPR_PC_DEAD,
    RESOURCE_ID_SPR_PTR,
    RESOURCE_ID_SPR_PTR_PUSH,
    RESOURCE_ID_SPR_PTR_DEAD,

    RESOURCE_ID_SPR_PT2,
    RESOURCE_ID_SPR_TECHPRIEST,
    RESOURCE_ID_SPR_TECHPRIEST_ANGERY,
    RESOURCE_ID_SPR_TECHPRIEST_PUSHED,
    RESOURCE_ID_SPR_TECHPRIEST_DEAD,
    RESOURCE_ID_SPR_SHOPKEEPER,

    RESOURCE_ID_LVL_HOME,
    RESOURCE_ID_LVL_SHOP,
    RESOURCE_ID_LVL_CATHEDRAL,
    RESOURCE_ID_LVL_MINE,
    RESOURCE_ID_LVL_OVERWORLD,
    RESOURCE_ID_LVL_CAVE,
};
#else
#include <pebble.h>
#endif

#endif
